#+TITLE: PROMICE AWS flags

* Table of contents                               :toc_2:noexport:
- [[#introduction][Introduction]]
- [[#flag-values][Flag values]]
- [[#application-of-flags][Application of flags]]
- [[#how-to-use-this-file][How to use this file]]
- [[#notes][Notes]]

* Introduction

This documents the flags used in PROMICE AWS products and the [[./flags.csv][flags DB]].

The flags DB is a self-documenting database of flag values, flag meanings, and advice where the flags should be applied. Flags may be applied elsewhere by the code, but will be explicitly applied based on this DB.

The first portion of the flags DB, denoted by "#" in the first column, is meant for human consumption. It documents the definition of each flag value.

The second portion of the flags DB (plus the header line) is composed by humans for the algorithm. It defines where each flag should be applied.

* Flag values

#+BEGIN_SRC bash :exports both
grep "^#" flags.csv | cut -d, -f4- | grep -v ",,"
# grep "^#" flags.csv | awk -F, 'BEGIN{OFS=",";} {print $5, $4, $6}' | grep -v ",,"
#+END_SRC

#+RESULTS:
| value | flag    | comment                                                               |
|     1 | CHECKME | Unverified suspicious. If cannot be classified further set to UNKNOWN |
|     2 | UNKNOWN | Verified suspicious but cannot be classified                          |
|     4 | NAN     | Known to be completely invalid. Set to NaN in early processing        |
|     8 | OOL     | Out of limits                                                         |
|    16 | OOL_2   | Flagged because another variable is OOL                               |
|    32 | VISIT   | Station visit                                                         |

* Application of flags

Flags are applied to one or more of a time span, a sensor, or a station. The format of [[./flags.csv]] is:

| t0   | t1   | station   | variable  | flag |
|------+------+-----------+-----------+------|
| <t0> | <t1> | <s> [<s>] | <v> [<v>] | <f>  |

Where
+ =<t0>= and =<t1>= are timestamps of the format =YYYY-MM-DD HH:MM:SS= or =n/a= to represent all times
  + Either both times must be defined, with =<t0>= earlier than =<t1>=, or both must be set to =n/a=
+ =<s>= is a space-separated list of station IDs
+ =<v>= is a space-separated list of variables
+ =<f>= is the flag value, where values have the meanings defined above
  + NOTE: Currently only flag =NAN= is handled by the code

As an example, the first 10 flag lines of the flags DB (at the time of this writing) are:

#+BEGIN_SRC bash :exports both
grep -v "^#" flags.csv | grep -v ",,," | head -n11
#+END_SRC

#+RESULTS:
| t0                  | t1                  | station | variable | flag | comment                                                                     |
| 2017-05-23 10:00:00 | 2017-06-10 11:00:00 | CEN     | *        |  NAN | suspicious early data including pressure logger which isn’t at the station? |
| n/a                 | n/a                 | CEN     | z_pt     |  NAN | not processed per V3 metadata.csv files                                     |

* How to use this file

+ When suspicious data is noticed, at a minimum the flag =1: Unverified suspicious= should be set, along with the relevant time(s), station(s), and sensor(s).
+ If the reason for the suspicious data is identified, the relevant flag should be set instead of =1=.
  + If a relevant flag does not exist create, add a new flag value and description in the first part of the flag DB.

The AWS processing code will use this database to either drop a column or row, set to NaN, or set a flag for the final output product.

* Notes

Architecture & implementation notes and thoughts...

+ The =ds= variable (an xarray dataset representing a NetCDF file) should have an identical =dsf= variable, where each cell contains the bitwise OR of flag values, initially all 0.
+ Only NAN flag modifies the data (=ds=), everything else adjusts values in =dsf=
  + As a final step, before writing L3 CSV data, =ds= is set to =NaN= where ~dsf != 0~
+ For more technical users (early processing levels or the L3 NetCDF files), =ds= and =dsf= can be merged and shared as a single file, or kept as separate files
+ If merging...
  + each variable has a paired flag (e.g. t_1 & t_1_flag; rh & rh_flag).
  + The paired flag could be an attribute of the variable (length: size(times))
+ Two global attributes, flag_and and flag_or, can provide the bitwise AND and OR of all the individual variable flags
  + flag_and shows when all variables have a flag set at a given time
  + flag_or shows when any variable has a flag set

