# Publish to GEUS Dataverse on package release
# https://github.com/IQSS/dataverse-uploader
on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install wheel requests
          python3 -m pip install --upgrade setuptools  
          pip install -U pyDataverse

      - id: getrelease
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: GEUS-Glaciology-and-Climate/pypromice
          
      - name: Send repo to Dataverse
        run: |
          python3 $GITHUB_WORKSPACE/main/.github/workflows/upload_to_dataverse.py \
          -token ${{secrets.DATAVERSE_TOKEN}} \
          -server https://dataverse.geus.dk \
          -doi doi:10.22008/FK2/3TSBF0 \
          -title ${{ steps.getrelease.outputs.release }} \
          -remove True \
          -publish False
