name: Compare NetCDF Outputs

on:
  pull_request:
    branches: [ main ]

jobs:
  compare-datasets:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out PR branch
      - name: Check out PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Install repo + dependencies
      - name: Install package (PR branch)
        run: |
          python -m pip install --upgrade pip
          pip install wheel xarray numpy
          python3 -m pip install --upgrade setuptools
          cd $GITHUB_WORKSPACE/${{ github.head_ref }}
          pip install .

      # Step 4: Run code on test data using PR branch
      - name: Run L0 to L3 processing using PR branch
        shell: bash
        run: |
          mkdir $GITHUB_WORKSPACE/out/
          mkdir $GITHUB_WORKSPACE/out/new/
          mkdir $GITHUB_WORKSPACE/data_issues
          get_l2 -c $GITHUB_WORKSPACE/${{ github.head_ref }}/tests/data/test_config1_raw.toml -i $GITHUB_WORKSPACE/${{ github.head_ref }}/tests/data/ --issues $GITHUB_WORKSPACE/data_issues -o $GITHUB_WORKSPACE/out/new/ --data_issues_path $GITHUB_WORKSPACE/data_issues
          get_l2tol3 -c $GITHUB_WORKSPACE/${{ github.head_ref }}/tests/data/station_configurations/TEST1.toml -i $GITHUB_WORKSPACE/out/new/L0toL2/TEST1/TEST1_hour.nc -o $GITHUB_WORKSPACE/out/new/ --data_issues_path $GITHUB_WORKSPACE/data_issues

      # Step 5: Check out main branch${i}
      - name: Check out main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      # Step 6: Reinstall repo from main branch
      - name: Install package (main branch)
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          python3 -m pip install --upgrade setuptools
          cd $GITHUB_WORKSPACE/main
          pip install .

      # Step 7: Run code on test data using main branch
      - name: Run L0 to L3 processing
        shell: bash
        run: |
          mkdir $GITHUB_WORKSPACE/out/original/
          get_l2 -c $GITHUB_WORKSPACE/main/tests/data/test_config1_raw.toml -i $GITHUB_WORKSPACE/main/tests/data/ --issues $GITHUB_WORKSPACE/data_issues -o $GITHUB_WORKSPACE/out/original/ --data_issues_path $GITHUB_WORKSPACE/data_issues
          get_l2tol3 -c $GITHUB_WORKSPACE/main/tests/data/station_configurations/TEST1.toml -i $GITHUB_WORKSPACE/out/original/L0toL2/TEST1/TEST1_hour.nc -o $GITHUB_WORKSPACE/out/original/ --data_issues_path $GITHUB_WORKSPACE/data_issues

      # Step 8: Run reporter
      - name: Run reporter
        run: |
          python $GITHUB_WORKSPACE/${{ github.head_ref }}/.github/workflows/data_output_reporter.py \
            -o $GITHUB_WORKSPACE/out/original/L2toL3/TEST1_hour.nc \
            -n $GITHUB_WORKSPACE/out/new/L2toL3/TEST1_hour.nc

      # Step 9: Comment on PR
      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: report.md
