name: Compare NetCDF Outputs

on:
  pull_request:
    branches: [ main ]

jobs:
  compare-datasets:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out PR branch
      - name: Check out PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Install repo + dependencies (PR branch)
      - name: Install package (PR branch)
        run: |
          python -m pip install --upgrade pip
          pip install wheel xarray numpy
          python3 -m pip install --upgrade setuptools
          pip install .

      # Step 4: Run code on test data using PR branch
      - name: Run L0 to L3 processing using PR branch
        shell: bash
        run: |
          mkdir -p out/new/
          mkdir -p data_issues/pr
          get_l2 -c tests/data/test_config1_raw.toml \
                 -i tests/data/ \
                 -o out/new/ \
                 --data_issues_path data_issues/pr
          get_l2tol3 -c tests/data/station_configurations/TEST1.toml \
                     -i out/new/TEST1/TEST1_hour.nc \
                     -o out/new/ \
                     --data_issues_path data_issues/pr

      # Step 4.5: Upload PR output file as artifact
      - name: Upload PR TEST1_hour.nc
        uses: actions/upload-artifact@v4
        with:
          name: pr-test1-hour
          path: |
            out/new/TEST1/TEST1_hour.nc

      # Step 5: Check out main branch
      - name: Check out main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      # Step 6: Reinstall repo from main branch
      - name: Install package (main branch)
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          python3 -m pip install --upgrade setuptools
          pip install .

      # Step 7: Run code on test data using main branch
      - name: Run L0 to L3 processing using main branch
        shell: bash
        run: |
          mkdir -p out/original/
          mkdir -p data_issues/main
          get_l2 -c tests/data/test_config1_raw.toml \
                 -i tests/data/ \
                 --issues data_issues/main \
                 -o out/original/ \
                 --data_issues_path data_issues/main
          get_l2tol3 -c tests/data/station_configurations/TEST1.toml \
                     -i out/original/TEST1/TEST1_hour.nc \
                     -o out/original/ \
                     --data_issues_path data_issues/main

      # Step 7.5: Download PR output artifact back into correct place
      - name: Download PR TEST1_hour.nc
        uses: actions/download-artifact@v4
        with:
          name: pr-test1-hour
          path: out/new/TEST1/

      # Step 8: Run reporter
      - name: Run reporter
        run: |
          python .github/workflows/data_output_reporter.py \
            -o out/original/TEST1/TEST1_hour.nc \
            -n out/new/TEST1/TEST1_hour.nc

      # Step 9: Comment on PR
      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: report.md

      # Step 9.5: Upload main branch output file as artifact
      - name: Upload main TEST1_hour.nc
        uses: actions/upload-artifact@v4
        with:
          name: main-test1-hour
          path: |
            out/original/TEST1/TEST1_hour.nc