name: Compare NetCDF Outputs

on:
  pull_request:
    branches: [ main ]

jobs:
  compare-datasets:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out PR branch
      - name: Check out PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Install repo + dependencies (PR branch)
      - name: Install package (PR branch)
        run: |
          python -m pip install --upgrade pip
          pip install wheel xarray numpy
          python3 -m pip install --upgrade setuptools
          cd $GITHUB_WORKSPACE
          pip install .

      # Step 4: Run code on test data using PR branch
      - name: Run L0 to L3 processing using PR branch
        shell: bash
        run: |
          mkdir -p $GITHUB_WORKSPACE/out/new/
          mkdir -p $GITHUB_WORKSPACE/data_issues/pr
          get_l2 -c $GITHUB_WORKSPACE/tests/data/test_config1_raw.toml \
                 -i $GITHUB_WORKSPACE/tests/data/ \
                 -o $GITHUB_WORKSPACE/out/new/ \
                 --data_issues_path $GITHUB_WORKSPACE/data_issues/pr
          get_l2tol3 -c $GITHUB_WORKSPACE/tests/data/station_configurations/TEST1.toml \
                     -i $GITHUB_WORKSPACE/out/new/TEST1/TEST1_hour.nc \
                     -o $GITHUB_WORKSPACE/out/new/ \
                     --data_issues_path $GITHUB_WORKSPACE/data_issues/pr

      # Step 5: Check out main branch
      - name: Check out main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      # Step 6: Reinstall repo from main branch
      - name: Install package (main branch)
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          python3 -m pip install --upgrade setuptools
          cd $GITHUB_WORKSPACE
          pip install .

      # Step 7: Run code on test data using main branch
      - name: Run L0 to L3 processing (main branch)
        shell: bash
        run: |
          mkdir -p $GITHUB_WORKSPACE/out/original/
          mkdir -p $GITHUB_WORKSPACE/data_issues/main
          get_l2 -c $GITHUB_WORKSPACE/tests/data/test_config1_raw.toml \
                 -i $GITHUB_WORKSPACE/tests/data/ \
                 --issues $GITHUB_WORKSPACE/data_issues/main \
                 -o $GITHUB_WORKSPACE/out/original/ \
                 --data_issues_path $GITHUB_WORKSPACE/data_issues/main
          get_l2tol3 -c $GITHUB_WORKSPACE/tests/data/station_configurations/TEST1.toml \
                     -i $GITHUB_WORKSPACE/out/original/TEST1/TEST1_hour.nc \
                     -o $GITHUB_WORKSPACE/out/original/ \
                     --data_issues_path $GITHUB_WORKSPACE/data_issues/main

      # Step 8: Run reporter
      - name: Run reporter
        run: |
          python $GITHUB_WORKSPACE/.github/workflows/data_output_reporter.py \
            -o $GITHUB_WORKSPACE/out/original/TEST1/TEST1_hour.nc \
            -n $GITHUB_WORKSPACE/out/new/TEST1/TEST1_hour.nc

      # Step 9: Comment on PR
      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: report.md
