on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: process_test
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          python3 -m pip install --upgrade setuptools
          cd $GITHUB_WORKSPACE/main
          pip install .  
      - name: Clone AWS Level 0 data repo for testing
        env:
          GITLAB_TOKEN : ${{ secrets.GITLAB_TOKEN }}
        run: | 
          cd $GITHUB_WORKSPACE
          git clone --depth 1 https://oauth2:${{ env.GITLAB_TOKEN }}@geusgitlab.geus.dk/glaciology-and-climate/promice/aws-l0.git
      - name: Run L0 to L2 processing
        env:
          TEST_STATION: KAN_U HUM
        shell: bash
        run: |
          mkdir $GITHUB_WORKSPACE/out/
          mkdir $GITHUB_WORKSPACE/out/L0toL2/
          mkdir $GITHUB_WORKSPACE/data_issues
          for i in $(echo ${{ env.TEST_STATION }} | tr ' ' '\n'); do
            python3 $GITHUB_WORKSPACE/main/src/pypromice/pipeline/get_l2.py -c $GITHUB_WORKSPACE/aws-l0/tx/config/$i.toml -i $GITHUB_WORKSPACE/aws-l0/tx --issues $GITHUB_WORKSPACE/data_issues -o $GITHUB_WORKSPACE/out/L0toL2/ --data_issues_path $GITHUB_WORKSPACE/data_issues
          done
      - name: Run L2 to L3 processing
        env:
          TEST_STATION: KAN_U HUM
        shell: bash
        run: |
          mkdir $GITHUB_WORKSPACE/out/L2toL3/
          for i in $(echo ${{ env.TEST_STATION }} | tr ' ' '\n'); do
            echo ${i}_hour.nc
            python3 $GITHUB_WORKSPACE/main/src/pypromice/pipeline/get_l2tol3.py -c $GITHUB_WORKSPACE/aws-l0/metadata/station_configurations/ -i $GITHUB_WORKSPACE/out/L0toL2/${i}/${i}_hour.nc -o $GITHUB_WORKSPACE/out/L2toL3/ --data_issues_path $GITHUB_WORKSPACE/data_issues
          done
      - name: Upload test output
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: out
          retention-days: 21
