on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
  workflow_dispatch:

jobs:
  test-ingest:
    name: unit_test (pypromice-ingest)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.10', '3.11']
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        shell: bash
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade setuptools
          cd $GITHUB_WORKSPACE
          pip install "packages/pypromice-ingest[google]"
          pip install pytest
      - name: Run unit tests
        shell: bash
        run: |
          python3 -m pytest packages/pypromice-ingest/tests/

  test-pipeline:
    name: unit_test (pypromice-pipeline)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.10', '3.11']
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        shell: bash
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install Bottleneck
          python3 -m pip install --upgrade setuptools
          cd $GITHUB_WORKSPACE
          pip install "packages/pypromice-ingest"
          pip install "packages/pypromice-pipeline[all]"
          pip install pytest
      - name: Run unit tests
        shell: bash
        run: |
          python3 -m pytest packages/pypromice-pipeline/tests/ tests/
